/* Numeric facts: pret/pokered d2704a63c26f9ba046ade877445216b3de0519a4. */
static const struct battle_move_fact gen1_moves[166]={
    {TYPE_NONE,0,0},
    {TYPE_NORMAL,2,40}, /* POUND */
    {TYPE_NORMAL,2,50}, /* KARATE_CHOP */
    {TYPE_NORMAL,2,15}, /* DOUBLESLAP */
    {TYPE_NORMAL,2,18}, /* COMET_PUNCH */
    {TYPE_NORMAL,2,80}, /* MEGA_PUNCH */
    {TYPE_NORMAL,2,40}, /* PAY_DAY */
    {TYPE_FIRE,2,75}, /* FIRE_PUNCH */
    {TYPE_ICE,2,75}, /* ICE_PUNCH */
    {TYPE_ELECTRIC,2,75}, /* THUNDERPUNCH */
    {TYPE_NORMAL,2,40}, /* SCRATCH */
    {TYPE_NORMAL,2,55}, /* VICEGRIP */
    {TYPE_NORMAL,4,1}, /* GUILLOTINE */
    {TYPE_NORMAL,2,80}, /* RAZOR_WIND */
    {TYPE_NORMAL,1,0}, /* SWORDS_DANCE */
    {TYPE_NORMAL,2,50}, /* CUT */
    {TYPE_NORMAL,2,40}, /* GUST */
    {TYPE_FLYING,2,35}, /* WING_ATTACK */
    {TYPE_NORMAL,1,0}, /* WHIRLWIND */
    {TYPE_FLYING,2,70}, /* FLY */
    {TYPE_NORMAL,2,15}, /* BIND */
    {TYPE_NORMAL,2,80}, /* SLAM */
    {TYPE_GRASS,2,35}, /* VINE_WHIP */
    {TYPE_NORMAL,2,65}, /* STOMP */
    {TYPE_FIGHTING,2,30}, /* DOUBLE_KICK */
    {TYPE_NORMAL,2,120}, /* MEGA_KICK */
    {TYPE_FIGHTING,2,70}, /* JUMP_KICK */
    {TYPE_FIGHTING,2,60}, /* ROLLING_KICK */
    {TYPE_NORMAL,1,0}, /* SAND_ATTACK */
    {TYPE_NORMAL,2,70}, /* HEADBUTT */
    {TYPE_NORMAL,2,65}, /* HORN_ATTACK */
    {TYPE_NORMAL,2,15}, /* FURY_ATTACK */
    {TYPE_NORMAL,4,1}, /* HORN_DRILL */
    {TYPE_NORMAL,2,35}, /* TACKLE */
    {TYPE_NORMAL,2,85}, /* BODY_SLAM */
    {TYPE_NORMAL,2,15}, /* WRAP */
    {TYPE_NORMAL,2,90}, /* TAKE_DOWN */
    {TYPE_NORMAL,2,90}, /* THRASH */
    {TYPE_NORMAL,2,100}, /* DOUBLE_EDGE */
    {TYPE_NORMAL,1,0}, /* TAIL_WHIP */
    {TYPE_POISON,2,15}, /* POISON_STING */
    {TYPE_BUG,2,25}, /* TWINEEDLE */
    {TYPE_BUG,2,14}, /* PIN_MISSILE */
    {TYPE_NORMAL,1,0}, /* LEER */
    {TYPE_NORMAL,2,60}, /* BITE */
    {TYPE_NORMAL,1,0}, /* GROWL */
    {TYPE_NORMAL,1,0}, /* ROAR */
    {TYPE_NORMAL,1,0}, /* SING */
    {TYPE_NORMAL,1,0}, /* SUPERSONIC */
    {TYPE_NORMAL,3,1}, /* SONICBOOM */
    {TYPE_NORMAL,1,0}, /* DISABLE */
    {TYPE_POISON,2,40}, /* ACID */
    {TYPE_FIRE,2,40}, /* EMBER */
    {TYPE_FIRE,2,95}, /* FLAMETHROWER */
    {TYPE_ICE,1,0}, /* MIST */
    {TYPE_WATER,2,40}, /* WATER_GUN */
    {TYPE_WATER,2,120}, /* HYDRO_PUMP */
    {TYPE_WATER,2,95}, /* SURF */
    {TYPE_ICE,2,95}, /* ICE_BEAM */
    {TYPE_ICE,2,120}, /* BLIZZARD */
    {TYPE_PSYCHIC,2,65}, /* PSYBEAM */
    {TYPE_WATER,2,65}, /* BUBBLEBEAM */
    {TYPE_ICE,2,65}, /* AURORA_BEAM */
    {TYPE_NORMAL,2,150}, /* HYPER_BEAM */
    {TYPE_FLYING,2,35}, /* PECK */
    {TYPE_FLYING,2,80}, /* DRILL_PECK */
    {TYPE_FIGHTING,2,80}, /* SUBMISSION */
    {TYPE_FIGHTING,2,50}, /* LOW_KICK */
    {TYPE_FIGHTING,5,1}, /* COUNTER */
    {TYPE_FIGHTING,3,1}, /* SEISMIC_TOSS */
    {TYPE_NORMAL,2,80}, /* STRENGTH */
    {TYPE_GRASS,2,20}, /* ABSORB */
    {TYPE_GRASS,2,40}, /* MEGA_DRAIN */
    {TYPE_GRASS,1,0}, /* LEECH_SEED */
    {TYPE_NORMAL,1,0}, /* GROWTH */
    {TYPE_GRASS,2,55}, /* RAZOR_LEAF */
    {TYPE_GRASS,2,120}, /* SOLARBEAM */
    {TYPE_POISON,1,0}, /* POISONPOWDER */
    {TYPE_GRASS,1,0}, /* STUN_SPORE */
    {TYPE_GRASS,1,0}, /* SLEEP_POWDER */
    {TYPE_GRASS,2,70}, /* PETAL_DANCE */
    {TYPE_BUG,1,0}, /* STRING_SHOT */
    {TYPE_DRAGON,3,1}, /* DRAGON_RAGE */
    {TYPE_FIRE,2,15}, /* FIRE_SPIN */
    {TYPE_ELECTRIC,2,40}, /* THUNDERSHOCK */
    {TYPE_ELECTRIC,2,95}, /* THUNDERBOLT */
    {TYPE_ELECTRIC,1,0}, /* THUNDER_WAVE */
    {TYPE_ELECTRIC,2,120}, /* THUNDER */
    {TYPE_ROCK,2,50}, /* ROCK_THROW */
    {TYPE_GROUND,2,100}, /* EARTHQUAKE */
    {TYPE_GROUND,4,1}, /* FISSURE */
    {TYPE_GROUND,2,100}, /* DIG */
    {TYPE_POISON,1,0}, /* TOXIC */
    {TYPE_PSYCHIC,2,50}, /* CONFUSION */
    {TYPE_PSYCHIC,2,90}, /* PSYCHIC_M */
    {TYPE_PSYCHIC,1,0}, /* HYPNOSIS */
    {TYPE_PSYCHIC,1,0}, /* MEDITATE */
    {TYPE_PSYCHIC,1,0}, /* AGILITY */
    {TYPE_NORMAL,2,40}, /* QUICK_ATTACK */
    {TYPE_NORMAL,2,20}, /* RAGE */
    {TYPE_PSYCHIC,1,0}, /* TELEPORT */
    {TYPE_GHOST,3,0}, /* NIGHT_SHADE */
    {TYPE_NORMAL,1,0}, /* MIMIC */
    {TYPE_NORMAL,1,0}, /* SCREECH */
    {TYPE_NORMAL,1,0}, /* DOUBLE_TEAM */
    {TYPE_NORMAL,1,0}, /* RECOVER */
    {TYPE_NORMAL,1,0}, /* HARDEN */
    {TYPE_NORMAL,1,0}, /* MINIMIZE */
    {TYPE_NORMAL,1,0}, /* SMOKESCREEN */
    {TYPE_GHOST,1,0}, /* CONFUSE_RAY */
    {TYPE_WATER,1,0}, /* WITHDRAW */
    {TYPE_NORMAL,1,0}, /* DEFENSE_CURL */
    {TYPE_PSYCHIC,1,0}, /* BARRIER */
    {TYPE_PSYCHIC,1,0}, /* LIGHT_SCREEN */
    {TYPE_ICE,1,0}, /* HAZE */
    {TYPE_PSYCHIC,1,0}, /* REFLECT */
    {TYPE_NORMAL,1,0}, /* FOCUS_ENERGY */
    {TYPE_NORMAL,5,0}, /* BIDE */
    {TYPE_NORMAL,5,0}, /* METRONOME */
    {TYPE_FLYING,5,0}, /* MIRROR_MOVE */
    {TYPE_NORMAL,2,130}, /* SELFDESTRUCT */
    {TYPE_NORMAL,2,100}, /* EGG_BOMB */
    {TYPE_GHOST,2,20}, /* LICK */
    {TYPE_POISON,2,20}, /* SMOG */
    {TYPE_POISON,2,65}, /* SLUDGE */
    {TYPE_GROUND,2,65}, /* BONE_CLUB */
    {TYPE_FIRE,2,120}, /* FIRE_BLAST */
    {TYPE_WATER,2,80}, /* WATERFALL */
    {TYPE_WATER,2,35}, /* CLAMP */
    {TYPE_NORMAL,2,60}, /* SWIFT */
    {TYPE_NORMAL,2,100}, /* SKULL_BASH */
    {TYPE_NORMAL,2,20}, /* SPIKE_CANNON */
    {TYPE_NORMAL,2,10}, /* CONSTRICT */
    {TYPE_PSYCHIC,1,0}, /* AMNESIA */
    {TYPE_PSYCHIC,1,0}, /* KINESIS */
    {TYPE_NORMAL,1,0}, /* SOFTBOILED */
    {TYPE_FIGHTING,2,85}, /* HI_JUMP_KICK */
    {TYPE_NORMAL,1,0}, /* GLARE */
    {TYPE_PSYCHIC,4,100}, /* DREAM_EATER */
    {TYPE_POISON,1,0}, /* POISON_GAS */
    {TYPE_NORMAL,2,15}, /* BARRAGE */
    {TYPE_BUG,2,20}, /* LEECH_LIFE */
    {TYPE_NORMAL,1,0}, /* LOVELY_KISS */
    {TYPE_FLYING,2,140}, /* SKY_ATTACK */
    {TYPE_NORMAL,1,0}, /* TRANSFORM */
    {TYPE_WATER,2,20}, /* BUBBLE */
    {TYPE_NORMAL,2,70}, /* DIZZY_PUNCH */
    {TYPE_GRASS,1,0}, /* SPORE */
    {TYPE_NORMAL,1,0}, /* FLASH */
    {TYPE_PSYCHIC,3,1}, /* PSYWAVE */
    {TYPE_NORMAL,1,0}, /* SPLASH */
    {TYPE_POISON,1,0}, /* ACID_ARMOR */
    {TYPE_WATER,2,90}, /* CRABHAMMER */
    {TYPE_NORMAL,2,170}, /* EXPLOSION */
    {TYPE_NORMAL,2,18}, /* FURY_SWIPES */
    {TYPE_GROUND,2,50}, /* BONEMERANG */
    {TYPE_PSYCHIC,1,0}, /* REST */
    {TYPE_ROCK,2,75}, /* ROCK_SLIDE */
    {TYPE_NORMAL,2,80}, /* HYPER_FANG */
    {TYPE_NORMAL,1,0}, /* SHARPEN */
    {TYPE_NORMAL,1,0}, /* CONVERSION */
    {TYPE_NORMAL,2,80}, /* TRI_ATTACK */
    {TYPE_NORMAL,3,1}, /* SUPER_FANG */
    {TYPE_NORMAL,2,70}, /* SLASH */
    {TYPE_NORMAL,1,0}, /* SUBSTITUTE */
    {TYPE_NORMAL,2,50}, /* STRUGGLE */
};
static const struct battle_matchup gen1_matchups[]={
    {TYPE_WATER,TYPE_FIRE,8},
    {TYPE_FIRE,TYPE_GRASS,8},
    {TYPE_FIRE,TYPE_ICE,8},
    {TYPE_GRASS,TYPE_WATER,8},
    {TYPE_ELECTRIC,TYPE_WATER,8},
    {TYPE_WATER,TYPE_ROCK,8},
    {TYPE_GROUND,TYPE_FLYING,0},
    {TYPE_WATER,TYPE_WATER,2},
    {TYPE_FIRE,TYPE_FIRE,2},
    {TYPE_ELECTRIC,TYPE_ELECTRIC,2},
    {TYPE_ICE,TYPE_ICE,2},
    {TYPE_GRASS,TYPE_GRASS,2},
    {TYPE_PSYCHIC,TYPE_PSYCHIC,2},
    {TYPE_FIRE,TYPE_WATER,2},
    {TYPE_GRASS,TYPE_FIRE,2},
    {TYPE_WATER,TYPE_GRASS,2},
    {TYPE_ELECTRIC,TYPE_GRASS,2},
    {TYPE_NORMAL,TYPE_ROCK,2},
    {TYPE_NORMAL,TYPE_GHOST,0},
    {TYPE_GHOST,TYPE_GHOST,8},
    {TYPE_FIRE,TYPE_BUG,8},
    {TYPE_FIRE,TYPE_ROCK,2},
    {TYPE_WATER,TYPE_GROUND,8},
    {TYPE_ELECTRIC,TYPE_GROUND,0},
    {TYPE_ELECTRIC,TYPE_FLYING,8},
    {TYPE_GRASS,TYPE_GROUND,8},
    {TYPE_GRASS,TYPE_BUG,2},
    {TYPE_GRASS,TYPE_POISON,2},
    {TYPE_GRASS,TYPE_ROCK,8},
    {TYPE_GRASS,TYPE_FLYING,2},
    {TYPE_ICE,TYPE_WATER,2},
    {TYPE_ICE,TYPE_GRASS,8},
    {TYPE_ICE,TYPE_GROUND,8},
    {TYPE_ICE,TYPE_FLYING,8},
    {TYPE_FIGHTING,TYPE_NORMAL,8},
    {TYPE_FIGHTING,TYPE_POISON,2},
    {TYPE_FIGHTING,TYPE_FLYING,2},
    {TYPE_FIGHTING,TYPE_PSYCHIC,2},
    {TYPE_FIGHTING,TYPE_BUG,2},
    {TYPE_FIGHTING,TYPE_ROCK,8},
    {TYPE_FIGHTING,TYPE_ICE,8},
    {TYPE_FIGHTING,TYPE_GHOST,0},
    {TYPE_POISON,TYPE_GRASS,8},
    {TYPE_POISON,TYPE_POISON,2},
    {TYPE_POISON,TYPE_GROUND,2},
    {TYPE_POISON,TYPE_BUG,8},
    {TYPE_POISON,TYPE_ROCK,2},
    {TYPE_POISON,TYPE_GHOST,2},
    {TYPE_GROUND,TYPE_FIRE,8},
    {TYPE_GROUND,TYPE_ELECTRIC,8},
    {TYPE_GROUND,TYPE_GRASS,2},
    {TYPE_GROUND,TYPE_BUG,2},
    {TYPE_GROUND,TYPE_ROCK,8},
    {TYPE_GROUND,TYPE_POISON,8},
    {TYPE_FLYING,TYPE_ELECTRIC,2},
    {TYPE_FLYING,TYPE_FIGHTING,8},
    {TYPE_FLYING,TYPE_BUG,8},
    {TYPE_FLYING,TYPE_GRASS,8},
    {TYPE_FLYING,TYPE_ROCK,2},
    {TYPE_PSYCHIC,TYPE_FIGHTING,8},
    {TYPE_PSYCHIC,TYPE_POISON,8},
    {TYPE_BUG,TYPE_FIRE,2},
    {TYPE_BUG,TYPE_GRASS,8},
    {TYPE_BUG,TYPE_FIGHTING,2},
    {TYPE_BUG,TYPE_FLYING,2},
    {TYPE_BUG,TYPE_PSYCHIC,8},
    {TYPE_BUG,TYPE_GHOST,2},
    {TYPE_BUG,TYPE_POISON,8},
    {TYPE_ROCK,TYPE_FIRE,8},
    {TYPE_ROCK,TYPE_FIGHTING,2},
    {TYPE_ROCK,TYPE_GROUND,2},
    {TYPE_ROCK,TYPE_FLYING,8},
    {TYPE_ROCK,TYPE_BUG,8},
    {TYPE_ROCK,TYPE_ICE,8},
    {TYPE_GHOST,TYPE_NORMAL,0},
    {TYPE_GHOST,TYPE_PSYCHIC,0},
    {TYPE_FIRE,TYPE_DRAGON,2},
    {TYPE_WATER,TYPE_DRAGON,2},
    {TYPE_ELECTRIC,TYPE_DRAGON,2},
    {TYPE_GRASS,TYPE_DRAGON,2},
    {TYPE_ICE,TYPE_DRAGON,8},
    {TYPE_DRAGON,TYPE_DRAGON,8},
};
