/* Numeric move/type facts from pinned pret/pokecrystal; see docs/move-effectiveness.md. */
static const struct move_data { enum pokemon_type type; unsigned rule; } moves[252] = {
    {TYPE_NONE, RULE_UNKNOWN},
    {TYPE_NORMAL, RULE_CHART}, /* POUND */
    {TYPE_FIGHTING, RULE_CHART}, /* KARATE_CHOP */
    {TYPE_NORMAL, RULE_CHART}, /* DOUBLESLAP */
    {TYPE_NORMAL, RULE_CHART}, /* COMET_PUNCH */
    {TYPE_NORMAL, RULE_CHART}, /* MEGA_PUNCH */
    {TYPE_NORMAL, RULE_CHART}, /* PAY_DAY */
    {TYPE_FIRE, RULE_CHART}, /* FIRE_PUNCH */
    {TYPE_ICE, RULE_CHART}, /* ICE_PUNCH */
    {TYPE_ELECTRIC, RULE_CHART}, /* THUNDERPUNCH */
    {TYPE_NORMAL, RULE_CHART}, /* SCRATCH */
    {TYPE_NORMAL, RULE_CHART}, /* VICEGRIP */
    {TYPE_NORMAL, RULE_FIXED}, /* GUILLOTINE */
    {TYPE_NORMAL, RULE_CHART}, /* RAZOR_WIND */
    {TYPE_NORMAL, RULE_STATUS}, /* SWORDS_DANCE */
    {TYPE_NORMAL, RULE_CHART}, /* CUT */
    {TYPE_FLYING, RULE_CHART}, /* GUST */
    {TYPE_FLYING, RULE_CHART}, /* WING_ATTACK */
    {TYPE_NORMAL, RULE_STATUS}, /* WHIRLWIND */
    {TYPE_FLYING, RULE_CHART}, /* FLY */
    {TYPE_NORMAL, RULE_CHART}, /* BIND */
    {TYPE_NORMAL, RULE_CHART}, /* SLAM */
    {TYPE_GRASS, RULE_CHART}, /* VINE_WHIP */
    {TYPE_NORMAL, RULE_CHART}, /* STOMP */
    {TYPE_FIGHTING, RULE_CHART}, /* DOUBLE_KICK */
    {TYPE_NORMAL, RULE_CHART}, /* MEGA_KICK */
    {TYPE_FIGHTING, RULE_CHART}, /* JUMP_KICK */
    {TYPE_FIGHTING, RULE_CHART}, /* ROLLING_KICK */
    {TYPE_GROUND, RULE_STATUS}, /* SAND_ATTACK */
    {TYPE_NORMAL, RULE_CHART}, /* HEADBUTT */
    {TYPE_NORMAL, RULE_CHART}, /* HORN_ATTACK */
    {TYPE_NORMAL, RULE_CHART}, /* FURY_ATTACK */
    {TYPE_NORMAL, RULE_FIXED}, /* HORN_DRILL */
    {TYPE_NORMAL, RULE_CHART}, /* TACKLE */
    {TYPE_NORMAL, RULE_CHART}, /* BODY_SLAM */
    {TYPE_NORMAL, RULE_CHART}, /* WRAP */
    {TYPE_NORMAL, RULE_CHART}, /* TAKE_DOWN */
    {TYPE_NORMAL, RULE_CHART}, /* THRASH */
    {TYPE_NORMAL, RULE_CHART}, /* DOUBLE_EDGE */
    {TYPE_NORMAL, RULE_STATUS}, /* TAIL_WHIP */
    {TYPE_POISON, RULE_CHART}, /* POISON_STING */
    {TYPE_BUG, RULE_CHART}, /* TWINEEDLE */
    {TYPE_BUG, RULE_CHART}, /* PIN_MISSILE */
    {TYPE_NORMAL, RULE_STATUS}, /* LEER */
    {TYPE_DARK, RULE_CHART}, /* BITE */
    {TYPE_NORMAL, RULE_STATUS}, /* GROWL */
    {TYPE_NORMAL, RULE_STATUS}, /* ROAR */
    {TYPE_NORMAL, RULE_STATUS}, /* SING */
    {TYPE_NORMAL, RULE_STATUS}, /* SUPERSONIC */
    {TYPE_NORMAL, RULE_FIXED}, /* SONICBOOM */
    {TYPE_NORMAL, RULE_STATUS}, /* DISABLE */
    {TYPE_POISON, RULE_CHART}, /* ACID */
    {TYPE_FIRE, RULE_CHART}, /* EMBER */
    {TYPE_FIRE, RULE_CHART}, /* FLAMETHROWER */
    {TYPE_ICE, RULE_STATUS}, /* MIST */
    {TYPE_WATER, RULE_CHART}, /* WATER_GUN */
    {TYPE_WATER, RULE_CHART}, /* HYDRO_PUMP */
    {TYPE_WATER, RULE_CHART}, /* SURF */
    {TYPE_ICE, RULE_CHART}, /* ICE_BEAM */
    {TYPE_ICE, RULE_CHART}, /* BLIZZARD */
    {TYPE_PSYCHIC, RULE_CHART}, /* PSYBEAM */
    {TYPE_WATER, RULE_CHART}, /* BUBBLEBEAM */
    {TYPE_ICE, RULE_CHART}, /* AURORA_BEAM */
    {TYPE_NORMAL, RULE_CHART}, /* HYPER_BEAM */
    {TYPE_FLYING, RULE_CHART}, /* PECK */
    {TYPE_FLYING, RULE_CHART}, /* DRILL_PECK */
    {TYPE_FIGHTING, RULE_CHART}, /* SUBMISSION */
    {TYPE_FIGHTING, RULE_CHART}, /* LOW_KICK */
    {TYPE_FIGHTING, RULE_CONDITIONAL}, /* COUNTER */
    {TYPE_FIGHTING, RULE_FIXED}, /* SEISMIC_TOSS */
    {TYPE_NORMAL, RULE_CHART}, /* STRENGTH */
    {TYPE_GRASS, RULE_CHART}, /* ABSORB */
    {TYPE_GRASS, RULE_CHART}, /* MEGA_DRAIN */
    {TYPE_GRASS, RULE_STATUS}, /* LEECH_SEED */
    {TYPE_NORMAL, RULE_STATUS}, /* GROWTH */
    {TYPE_GRASS, RULE_CHART}, /* RAZOR_LEAF */
    {TYPE_GRASS, RULE_CHART}, /* SOLARBEAM */
    {TYPE_POISON, RULE_STATUS}, /* POISONPOWDER */
    {TYPE_GRASS, RULE_STATUS}, /* STUN_SPORE */
    {TYPE_GRASS, RULE_STATUS}, /* SLEEP_POWDER */
    {TYPE_GRASS, RULE_CHART}, /* PETAL_DANCE */
    {TYPE_BUG, RULE_STATUS}, /* STRING_SHOT */
    {TYPE_DRAGON, RULE_FIXED}, /* DRAGON_RAGE */
    {TYPE_FIRE, RULE_CHART}, /* FIRE_SPIN */
    {TYPE_ELECTRIC, RULE_CHART}, /* THUNDERSHOCK */
    {TYPE_ELECTRIC, RULE_CHART}, /* THUNDERBOLT */
    {TYPE_ELECTRIC, RULE_STATUS}, /* THUNDER_WAVE */
    {TYPE_ELECTRIC, RULE_CHART}, /* THUNDER */
    {TYPE_ROCK, RULE_CHART}, /* ROCK_THROW */
    {TYPE_GROUND, RULE_CHART}, /* EARTHQUAKE */
    {TYPE_GROUND, RULE_FIXED}, /* FISSURE */
    {TYPE_GROUND, RULE_CHART}, /* DIG */
    {TYPE_POISON, RULE_STATUS}, /* TOXIC */
    {TYPE_PSYCHIC, RULE_CHART}, /* CONFUSION */
    {TYPE_PSYCHIC, RULE_CHART}, /* PSYCHIC_M */
    {TYPE_PSYCHIC, RULE_STATUS}, /* HYPNOSIS */
    {TYPE_PSYCHIC, RULE_STATUS}, /* MEDITATE */
    {TYPE_PSYCHIC, RULE_STATUS}, /* AGILITY */
    {TYPE_NORMAL, RULE_CHART}, /* QUICK_ATTACK */
    {TYPE_NORMAL, RULE_CHART}, /* RAGE */
    {TYPE_PSYCHIC, RULE_STATUS}, /* TELEPORT */
    {TYPE_GHOST, RULE_FIXED}, /* NIGHT_SHADE */
    {TYPE_NORMAL, RULE_STATUS}, /* MIMIC */
    {TYPE_NORMAL, RULE_STATUS}, /* SCREECH */
    {TYPE_NORMAL, RULE_STATUS}, /* DOUBLE_TEAM */
    {TYPE_NORMAL, RULE_STATUS}, /* RECOVER */
    {TYPE_NORMAL, RULE_STATUS}, /* HARDEN */
    {TYPE_NORMAL, RULE_STATUS}, /* MINIMIZE */
    {TYPE_NORMAL, RULE_STATUS}, /* SMOKESCREEN */
    {TYPE_GHOST, RULE_STATUS}, /* CONFUSE_RAY */
    {TYPE_WATER, RULE_STATUS}, /* WITHDRAW */
    {TYPE_NORMAL, RULE_STATUS}, /* DEFENSE_CURL */
    {TYPE_PSYCHIC, RULE_STATUS}, /* BARRIER */
    {TYPE_PSYCHIC, RULE_STATUS}, /* LIGHT_SCREEN */
    {TYPE_ICE, RULE_STATUS}, /* HAZE */
    {TYPE_PSYCHIC, RULE_STATUS}, /* REFLECT */
    {TYPE_NORMAL, RULE_STATUS}, /* FOCUS_ENERGY */
    {TYPE_NORMAL, RULE_CONDITIONAL}, /* BIDE */
    {TYPE_NORMAL, RULE_UNKNOWN}, /* METRONOME */
    {TYPE_FLYING, RULE_UNKNOWN}, /* MIRROR_MOVE */
    {TYPE_NORMAL, RULE_CHART}, /* SELFDESTRUCT */
    {TYPE_NORMAL, RULE_CHART}, /* EGG_BOMB */
    {TYPE_GHOST, RULE_CHART}, /* LICK */
    {TYPE_POISON, RULE_CHART}, /* SMOG */
    {TYPE_POISON, RULE_CHART}, /* SLUDGE */
    {TYPE_GROUND, RULE_CHART}, /* BONE_CLUB */
    {TYPE_FIRE, RULE_CHART}, /* FIRE_BLAST */
    {TYPE_WATER, RULE_CHART}, /* WATERFALL */
    {TYPE_WATER, RULE_CHART}, /* CLAMP */
    {TYPE_NORMAL, RULE_CHART}, /* SWIFT */
    {TYPE_NORMAL, RULE_CHART}, /* SKULL_BASH */
    {TYPE_NORMAL, RULE_CHART}, /* SPIKE_CANNON */
    {TYPE_NORMAL, RULE_CHART}, /* CONSTRICT */
    {TYPE_PSYCHIC, RULE_STATUS}, /* AMNESIA */
    {TYPE_PSYCHIC, RULE_STATUS}, /* KINESIS */
    {TYPE_NORMAL, RULE_STATUS}, /* SOFTBOILED */
    {TYPE_FIGHTING, RULE_CHART}, /* HI_JUMP_KICK */
    {TYPE_NORMAL, RULE_STATUS}, /* GLARE */
    {TYPE_PSYCHIC, RULE_CHART}, /* DREAM_EATER */
    {TYPE_POISON, RULE_STATUS}, /* POISON_GAS */
    {TYPE_NORMAL, RULE_CHART}, /* BARRAGE */
    {TYPE_BUG, RULE_CHART}, /* LEECH_LIFE */
    {TYPE_NORMAL, RULE_STATUS}, /* LOVELY_KISS */
    {TYPE_FLYING, RULE_CHART}, /* SKY_ATTACK */
    {TYPE_NORMAL, RULE_STATUS}, /* TRANSFORM */
    {TYPE_WATER, RULE_CHART}, /* BUBBLE */
    {TYPE_NORMAL, RULE_CHART}, /* DIZZY_PUNCH */
    {TYPE_GRASS, RULE_STATUS}, /* SPORE */
    {TYPE_NORMAL, RULE_STATUS}, /* FLASH */
    {TYPE_PSYCHIC, RULE_FIXED}, /* PSYWAVE */
    {TYPE_NORMAL, RULE_STATUS}, /* SPLASH */
    {TYPE_POISON, RULE_STATUS}, /* ACID_ARMOR */
    {TYPE_WATER, RULE_CHART}, /* CRABHAMMER */
    {TYPE_NORMAL, RULE_CHART}, /* EXPLOSION */
    {TYPE_NORMAL, RULE_CHART}, /* FURY_SWIPES */
    {TYPE_GROUND, RULE_CHART}, /* BONEMERANG */
    {TYPE_PSYCHIC, RULE_STATUS}, /* REST */
    {TYPE_ROCK, RULE_CHART}, /* ROCK_SLIDE */
    {TYPE_NORMAL, RULE_CHART}, /* HYPER_FANG */
    {TYPE_NORMAL, RULE_STATUS}, /* SHARPEN */
    {TYPE_NORMAL, RULE_STATUS}, /* CONVERSION */
    {TYPE_NORMAL, RULE_CHART}, /* TRI_ATTACK */
    {TYPE_NORMAL, RULE_FIXED}, /* SUPER_FANG */
    {TYPE_NORMAL, RULE_CHART}, /* SLASH */
    {TYPE_NORMAL, RULE_STATUS}, /* SUBSTITUTE */
    {TYPE_NORMAL, RULE_TYPELESS}, /* STRUGGLE */
    {TYPE_NORMAL, RULE_STATUS}, /* SKETCH */
    {TYPE_FIGHTING, RULE_CHART}, /* TRIPLE_KICK */
    {TYPE_DARK, RULE_CHART}, /* THIEF */
    {TYPE_BUG, RULE_STATUS}, /* SPIDER_WEB */
    {TYPE_NORMAL, RULE_STATUS}, /* MIND_READER */
    {TYPE_GHOST, RULE_STATUS}, /* NIGHTMARE */
    {TYPE_FIRE, RULE_CHART}, /* FLAME_WHEEL */
    {TYPE_NORMAL, RULE_CHART}, /* SNORE */
    {TYPE_NONE, RULE_STATUS}, /* CURSE */
    {TYPE_NORMAL, RULE_CHART}, /* FLAIL */
    {TYPE_NORMAL, RULE_STATUS}, /* CONVERSION2 */
    {TYPE_FLYING, RULE_CHART}, /* AEROBLAST */
    {TYPE_GRASS, RULE_STATUS}, /* COTTON_SPORE */
    {TYPE_FIGHTING, RULE_CHART}, /* REVERSAL */
    {TYPE_GHOST, RULE_STATUS}, /* SPITE */
    {TYPE_ICE, RULE_CHART}, /* POWDER_SNOW */
    {TYPE_NORMAL, RULE_STATUS}, /* PROTECT */
    {TYPE_FIGHTING, RULE_CHART}, /* MACH_PUNCH */
    {TYPE_NORMAL, RULE_STATUS}, /* SCARY_FACE */
    {TYPE_DARK, RULE_CHART}, /* FAINT_ATTACK */
    {TYPE_NORMAL, RULE_STATUS}, /* SWEET_KISS */
    {TYPE_NORMAL, RULE_STATUS}, /* BELLY_DRUM */
    {TYPE_POISON, RULE_CHART}, /* SLUDGE_BOMB */
    {TYPE_GROUND, RULE_CHART}, /* MUD_SLAP */
    {TYPE_WATER, RULE_CHART}, /* OCTAZOOKA */
    {TYPE_GROUND, RULE_STATUS}, /* SPIKES */
    {TYPE_ELECTRIC, RULE_CHART}, /* ZAP_CANNON */
    {TYPE_NORMAL, RULE_STATUS}, /* FORESIGHT */
    {TYPE_GHOST, RULE_STATUS}, /* DESTINY_BOND */
    {TYPE_NORMAL, RULE_STATUS}, /* PERISH_SONG */
    {TYPE_ICE, RULE_CHART}, /* ICY_WIND */
    {TYPE_FIGHTING, RULE_STATUS}, /* DETECT */
    {TYPE_GROUND, RULE_CHART}, /* BONE_RUSH */
    {TYPE_NORMAL, RULE_STATUS}, /* LOCK_ON */
    {TYPE_DRAGON, RULE_CHART}, /* OUTRAGE */
    {TYPE_ROCK, RULE_STATUS}, /* SANDSTORM */
    {TYPE_GRASS, RULE_CHART}, /* GIGA_DRAIN */
    {TYPE_NORMAL, RULE_STATUS}, /* ENDURE */
    {TYPE_NORMAL, RULE_STATUS}, /* CHARM */
    {TYPE_ROCK, RULE_CHART}, /* ROLLOUT */
    {TYPE_NORMAL, RULE_CHART}, /* FALSE_SWIPE */
    {TYPE_NORMAL, RULE_STATUS}, /* SWAGGER */
    {TYPE_NORMAL, RULE_STATUS}, /* MILK_DRINK */
    {TYPE_ELECTRIC, RULE_CHART}, /* SPARK */
    {TYPE_BUG, RULE_CHART}, /* FURY_CUTTER */
    {TYPE_STEEL, RULE_CHART}, /* STEEL_WING */
    {TYPE_NORMAL, RULE_STATUS}, /* MEAN_LOOK */
    {TYPE_NORMAL, RULE_STATUS}, /* ATTRACT */
    {TYPE_NORMAL, RULE_UNKNOWN}, /* SLEEP_TALK */
    {TYPE_NORMAL, RULE_STATUS}, /* HEAL_BELL */
    {TYPE_NORMAL, RULE_CHART}, /* RETURN */
    {TYPE_NORMAL, RULE_CHART}, /* PRESENT */
    {TYPE_NORMAL, RULE_CHART}, /* FRUSTRATION */
    {TYPE_NORMAL, RULE_STATUS}, /* SAFEGUARD */
    {TYPE_NORMAL, RULE_STATUS}, /* PAIN_SPLIT */
    {TYPE_FIRE, RULE_CHART}, /* SACRED_FIRE */
    {TYPE_GROUND, RULE_CHART}, /* MAGNITUDE */
    {TYPE_FIGHTING, RULE_CHART}, /* DYNAMICPUNCH */
    {TYPE_BUG, RULE_CHART}, /* MEGAHORN */
    {TYPE_DRAGON, RULE_CHART}, /* DRAGONBREATH */
    {TYPE_NORMAL, RULE_STATUS}, /* BATON_PASS */
    {TYPE_NORMAL, RULE_STATUS}, /* ENCORE */
    {TYPE_DARK, RULE_CHART}, /* PURSUIT */
    {TYPE_NORMAL, RULE_CHART}, /* RAPID_SPIN */
    {TYPE_NORMAL, RULE_STATUS}, /* SWEET_SCENT */
    {TYPE_STEEL, RULE_CHART}, /* IRON_TAIL */
    {TYPE_STEEL, RULE_CHART}, /* METAL_CLAW */
    {TYPE_FIGHTING, RULE_CHART}, /* VITAL_THROW */
    {TYPE_NORMAL, RULE_STATUS}, /* MORNING_SUN */
    {TYPE_GRASS, RULE_STATUS}, /* SYNTHESIS */
    {TYPE_NORMAL, RULE_STATUS}, /* MOONLIGHT */
    {TYPE_NORMAL, RULE_HIDDEN}, /* HIDDEN_POWER */
    {TYPE_FIGHTING, RULE_CHART}, /* CROSS_CHOP */
    {TYPE_DRAGON, RULE_CHART}, /* TWISTER */
    {TYPE_WATER, RULE_STATUS}, /* RAIN_DANCE */
    {TYPE_FIRE, RULE_STATUS}, /* SUNNY_DAY */
    {TYPE_DARK, RULE_CHART}, /* CRUNCH */
    {TYPE_PSYCHIC, RULE_CONDITIONAL}, /* MIRROR_COAT */
    {TYPE_NORMAL, RULE_STATUS}, /* PSYCH_UP */
    {TYPE_NORMAL, RULE_CHART}, /* EXTREMESPEED */
    {TYPE_ROCK, RULE_CHART}, /* ANCIENTPOWER */
    {TYPE_GHOST, RULE_CHART}, /* SHADOW_BALL */
    {TYPE_PSYCHIC, RULE_TYPELESS}, /* FUTURE_SIGHT */
    {TYPE_FIGHTING, RULE_CHART}, /* ROCK_SMASH */
    {TYPE_WATER, RULE_CHART}, /* WHIRLPOOL */
    {TYPE_DARK, RULE_TYPELESS}, /* BEAT_UP */
};
static const struct matchup { enum pokemon_type attack, defense; unsigned quarters; } matchups[] = {
    {TYPE_NORMAL, TYPE_ROCK, 2},
    {TYPE_NORMAL, TYPE_STEEL, 2},
    {TYPE_FIRE, TYPE_FIRE, 2},
    {TYPE_FIRE, TYPE_WATER, 2},
    {TYPE_FIRE, TYPE_GRASS, 8},
    {TYPE_FIRE, TYPE_ICE, 8},
    {TYPE_FIRE, TYPE_BUG, 8},
    {TYPE_FIRE, TYPE_ROCK, 2},
    {TYPE_FIRE, TYPE_DRAGON, 2},
    {TYPE_FIRE, TYPE_STEEL, 8},
    {TYPE_WATER, TYPE_FIRE, 8},
    {TYPE_WATER, TYPE_WATER, 2},
    {TYPE_WATER, TYPE_GRASS, 2},
    {TYPE_WATER, TYPE_GROUND, 8},
    {TYPE_WATER, TYPE_ROCK, 8},
    {TYPE_WATER, TYPE_DRAGON, 2},
    {TYPE_ELECTRIC, TYPE_WATER, 8},
    {TYPE_ELECTRIC, TYPE_ELECTRIC, 2},
    {TYPE_ELECTRIC, TYPE_GRASS, 2},
    {TYPE_ELECTRIC, TYPE_GROUND, 0},
    {TYPE_ELECTRIC, TYPE_FLYING, 8},
    {TYPE_ELECTRIC, TYPE_DRAGON, 2},
    {TYPE_GRASS, TYPE_FIRE, 2},
    {TYPE_GRASS, TYPE_WATER, 8},
    {TYPE_GRASS, TYPE_GRASS, 2},
    {TYPE_GRASS, TYPE_POISON, 2},
    {TYPE_GRASS, TYPE_GROUND, 8},
    {TYPE_GRASS, TYPE_FLYING, 2},
    {TYPE_GRASS, TYPE_BUG, 2},
    {TYPE_GRASS, TYPE_ROCK, 8},
    {TYPE_GRASS, TYPE_DRAGON, 2},
    {TYPE_GRASS, TYPE_STEEL, 2},
    {TYPE_ICE, TYPE_WATER, 2},
    {TYPE_ICE, TYPE_GRASS, 8},
    {TYPE_ICE, TYPE_ICE, 2},
    {TYPE_ICE, TYPE_GROUND, 8},
    {TYPE_ICE, TYPE_FLYING, 8},
    {TYPE_ICE, TYPE_DRAGON, 8},
    {TYPE_ICE, TYPE_STEEL, 2},
    {TYPE_ICE, TYPE_FIRE, 2},
    {TYPE_FIGHTING, TYPE_NORMAL, 8},
    {TYPE_FIGHTING, TYPE_ICE, 8},
    {TYPE_FIGHTING, TYPE_POISON, 2},
    {TYPE_FIGHTING, TYPE_FLYING, 2},
    {TYPE_FIGHTING, TYPE_PSYCHIC, 2},
    {TYPE_FIGHTING, TYPE_BUG, 2},
    {TYPE_FIGHTING, TYPE_ROCK, 8},
    {TYPE_FIGHTING, TYPE_DARK, 8},
    {TYPE_FIGHTING, TYPE_STEEL, 8},
    {TYPE_POISON, TYPE_GRASS, 8},
    {TYPE_POISON, TYPE_POISON, 2},
    {TYPE_POISON, TYPE_GROUND, 2},
    {TYPE_POISON, TYPE_ROCK, 2},
    {TYPE_POISON, TYPE_GHOST, 2},
    {TYPE_POISON, TYPE_STEEL, 0},
    {TYPE_GROUND, TYPE_FIRE, 8},
    {TYPE_GROUND, TYPE_ELECTRIC, 8},
    {TYPE_GROUND, TYPE_GRASS, 2},
    {TYPE_GROUND, TYPE_POISON, 8},
    {TYPE_GROUND, TYPE_FLYING, 0},
    {TYPE_GROUND, TYPE_BUG, 2},
    {TYPE_GROUND, TYPE_ROCK, 8},
    {TYPE_GROUND, TYPE_STEEL, 8},
    {TYPE_FLYING, TYPE_ELECTRIC, 2},
    {TYPE_FLYING, TYPE_GRASS, 8},
    {TYPE_FLYING, TYPE_FIGHTING, 8},
    {TYPE_FLYING, TYPE_BUG, 8},
    {TYPE_FLYING, TYPE_ROCK, 2},
    {TYPE_FLYING, TYPE_STEEL, 2},
    {TYPE_PSYCHIC, TYPE_FIGHTING, 8},
    {TYPE_PSYCHIC, TYPE_POISON, 8},
    {TYPE_PSYCHIC, TYPE_PSYCHIC, 2},
    {TYPE_PSYCHIC, TYPE_DARK, 0},
    {TYPE_PSYCHIC, TYPE_STEEL, 2},
    {TYPE_BUG, TYPE_FIRE, 2},
    {TYPE_BUG, TYPE_GRASS, 8},
    {TYPE_BUG, TYPE_FIGHTING, 2},
    {TYPE_BUG, TYPE_POISON, 2},
    {TYPE_BUG, TYPE_FLYING, 2},
    {TYPE_BUG, TYPE_PSYCHIC, 8},
    {TYPE_BUG, TYPE_GHOST, 2},
    {TYPE_BUG, TYPE_DARK, 8},
    {TYPE_BUG, TYPE_STEEL, 2},
    {TYPE_ROCK, TYPE_FIRE, 8},
    {TYPE_ROCK, TYPE_ICE, 8},
    {TYPE_ROCK, TYPE_FIGHTING, 2},
    {TYPE_ROCK, TYPE_GROUND, 2},
    {TYPE_ROCK, TYPE_FLYING, 8},
    {TYPE_ROCK, TYPE_BUG, 8},
    {TYPE_ROCK, TYPE_STEEL, 2},
    {TYPE_GHOST, TYPE_NORMAL, 0},
    {TYPE_GHOST, TYPE_PSYCHIC, 8},
    {TYPE_GHOST, TYPE_DARK, 2},
    {TYPE_GHOST, TYPE_STEEL, 2},
    {TYPE_GHOST, TYPE_GHOST, 8},
    {TYPE_DRAGON, TYPE_DRAGON, 8},
    {TYPE_DRAGON, TYPE_STEEL, 2},
    {TYPE_DARK, TYPE_FIGHTING, 2},
    {TYPE_DARK, TYPE_PSYCHIC, 8},
    {TYPE_DARK, TYPE_GHOST, 8},
    {TYPE_DARK, TYPE_DARK, 2},
    {TYPE_DARK, TYPE_STEEL, 2},
    {TYPE_STEEL, TYPE_FIRE, 2},
    {TYPE_STEEL, TYPE_WATER, 2},
    {TYPE_STEEL, TYPE_ELECTRIC, 2},
    {TYPE_STEEL, TYPE_ICE, 8},
    {TYPE_STEEL, TYPE_ROCK, 8},
    {TYPE_STEEL, TYPE_STEEL, 2},
    {TYPE_NORMAL, TYPE_GHOST, 0},
    {TYPE_FIGHTING, TYPE_GHOST, 0},
};

