/* Numeric facts: pret/pokeemerald 731ad5bfd6e6f265508d0efcca0ba42f9dcf5881. */
static const struct battle_move_fact gen3_moves[355]={
    {TYPE_NORMAL,1,0}, /* NONE */
    {TYPE_NORMAL,2,40}, /* POUND */
    {TYPE_FIGHTING,2,50}, /* KARATE_CHOP */
    {TYPE_NORMAL,2,15}, /* DOUBLE_SLAP */
    {TYPE_NORMAL,2,18}, /* COMET_PUNCH */
    {TYPE_NORMAL,2,80}, /* MEGA_PUNCH */
    {TYPE_NORMAL,2,40}, /* PAY_DAY */
    {TYPE_FIRE,2,75}, /* FIRE_PUNCH */
    {TYPE_ICE,2,75}, /* ICE_PUNCH */
    {TYPE_ELECTRIC,2,75}, /* THUNDER_PUNCH */
    {TYPE_NORMAL,2,40}, /* SCRATCH */
    {TYPE_NORMAL,2,55}, /* VICE_GRIP */
    {TYPE_NORMAL,4,1}, /* GUILLOTINE */
    {TYPE_NORMAL,2,80}, /* RAZOR_WIND */
    {TYPE_NORMAL,1,0}, /* SWORDS_DANCE */
    {TYPE_NORMAL,2,50}, /* CUT */
    {TYPE_FLYING,2,40}, /* GUST */
    {TYPE_FLYING,2,60}, /* WING_ATTACK */
    {TYPE_NORMAL,1,0}, /* WHIRLWIND */
    {TYPE_FLYING,2,70}, /* FLY */
    {TYPE_NORMAL,2,15}, /* BIND */
    {TYPE_NORMAL,2,80}, /* SLAM */
    {TYPE_GRASS,2,35}, /* VINE_WHIP */
    {TYPE_NORMAL,2,65}, /* STOMP */
    {TYPE_FIGHTING,2,30}, /* DOUBLE_KICK */
    {TYPE_NORMAL,2,120}, /* MEGA_KICK */
    {TYPE_FIGHTING,2,70}, /* JUMP_KICK */
    {TYPE_FIGHTING,2,60}, /* ROLLING_KICK */
    {TYPE_GROUND,1,0}, /* SAND_ATTACK */
    {TYPE_NORMAL,2,70}, /* HEADBUTT */
    {TYPE_NORMAL,2,65}, /* HORN_ATTACK */
    {TYPE_NORMAL,2,15}, /* FURY_ATTACK */
    {TYPE_NORMAL,4,1}, /* HORN_DRILL */
    {TYPE_NORMAL,2,35}, /* TACKLE */
    {TYPE_NORMAL,2,85}, /* BODY_SLAM */
    {TYPE_NORMAL,2,15}, /* WRAP */
    {TYPE_NORMAL,2,90}, /* TAKE_DOWN */
    {TYPE_NORMAL,2,90}, /* THRASH */
    {TYPE_NORMAL,2,120}, /* DOUBLE_EDGE */
    {TYPE_NORMAL,1,0}, /* TAIL_WHIP */
    {TYPE_POISON,2,15}, /* POISON_STING */
    {TYPE_BUG,2,25}, /* TWINEEDLE */
    {TYPE_BUG,2,14}, /* PIN_MISSILE */
    {TYPE_NORMAL,1,0}, /* LEER */
    {TYPE_DARK,2,60}, /* BITE */
    {TYPE_NORMAL,1,0}, /* GROWL */
    {TYPE_NORMAL,1,0}, /* ROAR */
    {TYPE_NORMAL,1,0}, /* SING */
    {TYPE_NORMAL,1,0}, /* SUPERSONIC */
    {TYPE_NORMAL,3,1}, /* SONIC_BOOM */
    {TYPE_NORMAL,1,0}, /* DISABLE */
    {TYPE_POISON,2,40}, /* ACID */
    {TYPE_FIRE,2,40}, /* EMBER */
    {TYPE_FIRE,2,95}, /* FLAMETHROWER */
    {TYPE_ICE,1,0}, /* MIST */
    {TYPE_WATER,2,40}, /* WATER_GUN */
    {TYPE_WATER,2,120}, /* HYDRO_PUMP */
    {TYPE_WATER,2,95}, /* SURF */
    {TYPE_ICE,2,95}, /* ICE_BEAM */
    {TYPE_ICE,2,120}, /* BLIZZARD */
    {TYPE_PSYCHIC,2,65}, /* PSYBEAM */
    {TYPE_WATER,2,65}, /* BUBBLE_BEAM */
    {TYPE_ICE,2,65}, /* AURORA_BEAM */
    {TYPE_NORMAL,2,150}, /* HYPER_BEAM */
    {TYPE_FLYING,2,35}, /* PECK */
    {TYPE_FLYING,2,80}, /* DRILL_PECK */
    {TYPE_FIGHTING,2,80}, /* SUBMISSION */
    {TYPE_FIGHTING,2,1}, /* LOW_KICK */
    {TYPE_FIGHTING,4,1}, /* COUNTER */
    {TYPE_FIGHTING,3,1}, /* SEISMIC_TOSS */
    {TYPE_NORMAL,2,80}, /* STRENGTH */
    {TYPE_GRASS,2,20}, /* ABSORB */
    {TYPE_GRASS,2,40}, /* MEGA_DRAIN */
    {TYPE_GRASS,1,0}, /* LEECH_SEED */
    {TYPE_NORMAL,1,0}, /* GROWTH */
    {TYPE_GRASS,2,55}, /* RAZOR_LEAF */
    {TYPE_GRASS,2,120}, /* SOLAR_BEAM */
    {TYPE_POISON,1,0}, /* POISON_POWDER */
    {TYPE_GRASS,1,0}, /* STUN_SPORE */
    {TYPE_GRASS,1,0}, /* SLEEP_POWDER */
    {TYPE_GRASS,2,70}, /* PETAL_DANCE */
    {TYPE_BUG,1,0}, /* STRING_SHOT */
    {TYPE_DRAGON,3,1}, /* DRAGON_RAGE */
    {TYPE_FIRE,2,15}, /* FIRE_SPIN */
    {TYPE_ELECTRIC,2,40}, /* THUNDER_SHOCK */
    {TYPE_ELECTRIC,2,95}, /* THUNDERBOLT */
    {TYPE_ELECTRIC,1,0}, /* THUNDER_WAVE */
    {TYPE_ELECTRIC,2,120}, /* THUNDER */
    {TYPE_ROCK,2,50}, /* ROCK_THROW */
    {TYPE_GROUND,2,100}, /* EARTHQUAKE */
    {TYPE_GROUND,4,1}, /* FISSURE */
    {TYPE_GROUND,2,60}, /* DIG */
    {TYPE_POISON,1,0}, /* TOXIC */
    {TYPE_PSYCHIC,2,50}, /* CONFUSION */
    {TYPE_PSYCHIC,2,90}, /* PSYCHIC */
    {TYPE_PSYCHIC,1,0}, /* HYPNOSIS */
    {TYPE_PSYCHIC,1,0}, /* MEDITATE */
    {TYPE_PSYCHIC,1,0}, /* AGILITY */
    {TYPE_NORMAL,2,40}, /* QUICK_ATTACK */
    {TYPE_NORMAL,2,20}, /* RAGE */
    {TYPE_PSYCHIC,1,0}, /* TELEPORT */
    {TYPE_GHOST,3,1}, /* NIGHT_SHADE */
    {TYPE_NORMAL,1,0}, /* MIMIC */
    {TYPE_NORMAL,1,0}, /* SCREECH */
    {TYPE_NORMAL,1,0}, /* DOUBLE_TEAM */
    {TYPE_NORMAL,1,0}, /* RECOVER */
    {TYPE_NORMAL,1,0}, /* HARDEN */
    {TYPE_NORMAL,1,0}, /* MINIMIZE */
    {TYPE_NORMAL,1,0}, /* SMOKESCREEN */
    {TYPE_GHOST,1,0}, /* CONFUSE_RAY */
    {TYPE_WATER,1,0}, /* WITHDRAW */
    {TYPE_NORMAL,1,0}, /* DEFENSE_CURL */
    {TYPE_PSYCHIC,1,0}, /* BARRIER */
    {TYPE_PSYCHIC,1,0}, /* LIGHT_SCREEN */
    {TYPE_ICE,1,0}, /* HAZE */
    {TYPE_PSYCHIC,1,0}, /* REFLECT */
    {TYPE_NORMAL,1,0}, /* FOCUS_ENERGY */
    {TYPE_NORMAL,5,1}, /* BIDE */
    {TYPE_NORMAL,5,0}, /* METRONOME */
    {TYPE_FLYING,5,0}, /* MIRROR_MOVE */
    {TYPE_NORMAL,2,200}, /* SELF_DESTRUCT */
    {TYPE_NORMAL,2,100}, /* EGG_BOMB */
    {TYPE_GHOST,2,20}, /* LICK */
    {TYPE_POISON,2,20}, /* SMOG */
    {TYPE_POISON,2,65}, /* SLUDGE */
    {TYPE_GROUND,2,65}, /* BONE_CLUB */
    {TYPE_FIRE,2,120}, /* FIRE_BLAST */
    {TYPE_WATER,2,80}, /* WATERFALL */
    {TYPE_WATER,2,35}, /* CLAMP */
    {TYPE_NORMAL,2,60}, /* SWIFT */
    {TYPE_NORMAL,2,100}, /* SKULL_BASH */
    {TYPE_NORMAL,2,20}, /* SPIKE_CANNON */
    {TYPE_NORMAL,2,10}, /* CONSTRICT */
    {TYPE_PSYCHIC,1,0}, /* AMNESIA */
    {TYPE_PSYCHIC,1,0}, /* KINESIS */
    {TYPE_NORMAL,1,0}, /* SOFT_BOILED */
    {TYPE_FIGHTING,2,85}, /* HI_JUMP_KICK */
    {TYPE_NORMAL,1,0}, /* GLARE */
    {TYPE_PSYCHIC,4,100}, /* DREAM_EATER */
    {TYPE_POISON,1,0}, /* POISON_GAS */
    {TYPE_NORMAL,2,15}, /* BARRAGE */
    {TYPE_BUG,2,20}, /* LEECH_LIFE */
    {TYPE_NORMAL,1,0}, /* LOVELY_KISS */
    {TYPE_FLYING,2,140}, /* SKY_ATTACK */
    {TYPE_NORMAL,1,0}, /* TRANSFORM */
    {TYPE_WATER,2,20}, /* BUBBLE */
    {TYPE_NORMAL,2,70}, /* DIZZY_PUNCH */
    {TYPE_GRASS,1,0}, /* SPORE */
    {TYPE_NORMAL,1,0}, /* FLASH */
    {TYPE_PSYCHIC,2,1}, /* PSYWAVE */
    {TYPE_NORMAL,1,0}, /* SPLASH */
    {TYPE_POISON,1,0}, /* ACID_ARMOR */
    {TYPE_WATER,2,90}, /* CRABHAMMER */
    {TYPE_NORMAL,2,250}, /* EXPLOSION */
    {TYPE_NORMAL,2,18}, /* FURY_SWIPES */
    {TYPE_GROUND,2,50}, /* BONEMERANG */
    {TYPE_PSYCHIC,1,0}, /* REST */
    {TYPE_ROCK,2,75}, /* ROCK_SLIDE */
    {TYPE_NORMAL,2,80}, /* HYPER_FANG */
    {TYPE_NORMAL,1,0}, /* SHARPEN */
    {TYPE_NORMAL,1,0}, /* CONVERSION */
    {TYPE_NORMAL,2,80}, /* TRI_ATTACK */
    {TYPE_NORMAL,3,1}, /* SUPER_FANG */
    {TYPE_NORMAL,2,70}, /* SLASH */
    {TYPE_NORMAL,1,0}, /* SUBSTITUTE */
    {TYPE_NORMAL,7,50}, /* STRUGGLE */
    {TYPE_NORMAL,1,0}, /* SKETCH */
    {TYPE_FIGHTING,2,10}, /* TRIPLE_KICK */
    {TYPE_DARK,2,40}, /* THIEF */
    {TYPE_BUG,1,0}, /* SPIDER_WEB */
    {TYPE_NORMAL,1,0}, /* MIND_READER */
    {TYPE_GHOST,1,0}, /* NIGHTMARE */
    {TYPE_FIRE,2,60}, /* FLAME_WHEEL */
    {TYPE_NORMAL,4,40}, /* SNORE */
    {TYPE_NONE,1,0}, /* CURSE */
    {TYPE_NORMAL,2,1}, /* FLAIL */
    {TYPE_NORMAL,1,0}, /* CONVERSION_2 */
    {TYPE_FLYING,2,100}, /* AEROBLAST */
    {TYPE_GRASS,1,0}, /* COTTON_SPORE */
    {TYPE_FIGHTING,2,1}, /* REVERSAL */
    {TYPE_GHOST,1,0}, /* SPITE */
    {TYPE_ICE,2,40}, /* POWDER_SNOW */
    {TYPE_NORMAL,1,0}, /* PROTECT */
    {TYPE_FIGHTING,2,40}, /* MACH_PUNCH */
    {TYPE_NORMAL,1,0}, /* SCARY_FACE */
    {TYPE_DARK,2,60}, /* FAINT_ATTACK */
    {TYPE_NORMAL,1,0}, /* SWEET_KISS */
    {TYPE_NORMAL,1,0}, /* BELLY_DRUM */
    {TYPE_POISON,2,90}, /* SLUDGE_BOMB */
    {TYPE_GROUND,2,20}, /* MUD_SLAP */
    {TYPE_WATER,2,65}, /* OCTAZOOKA */
    {TYPE_GROUND,1,0}, /* SPIKES */
    {TYPE_ELECTRIC,2,100}, /* ZAP_CANNON */
    {TYPE_NORMAL,1,0}, /* FORESIGHT */
    {TYPE_GHOST,1,0}, /* DESTINY_BOND */
    {TYPE_NORMAL,1,0}, /* PERISH_SONG */
    {TYPE_ICE,2,55}, /* ICY_WIND */
    {TYPE_FIGHTING,1,0}, /* DETECT */
    {TYPE_GROUND,2,25}, /* BONE_RUSH */
    {TYPE_NORMAL,1,0}, /* LOCK_ON */
    {TYPE_DRAGON,2,90}, /* OUTRAGE */
    {TYPE_ROCK,1,0}, /* SANDSTORM */
    {TYPE_GRASS,2,60}, /* GIGA_DRAIN */
    {TYPE_NORMAL,1,0}, /* ENDURE */
    {TYPE_NORMAL,1,0}, /* CHARM */
    {TYPE_ROCK,2,30}, /* ROLLOUT */
    {TYPE_NORMAL,2,40}, /* FALSE_SWIPE */
    {TYPE_NORMAL,1,0}, /* SWAGGER */
    {TYPE_NORMAL,1,0}, /* MILK_DRINK */
    {TYPE_ELECTRIC,2,65}, /* SPARK */
    {TYPE_BUG,2,10}, /* FURY_CUTTER */
    {TYPE_STEEL,2,70}, /* STEEL_WING */
    {TYPE_NORMAL,1,0}, /* MEAN_LOOK */
    {TYPE_NORMAL,1,0}, /* ATTRACT */
    {TYPE_NORMAL,5,0}, /* SLEEP_TALK */
    {TYPE_NORMAL,1,0}, /* HEAL_BELL */
    {TYPE_NORMAL,2,1}, /* RETURN */
    {TYPE_NORMAL,2,1}, /* PRESENT */
    {TYPE_NORMAL,2,1}, /* FRUSTRATION */
    {TYPE_NORMAL,1,0}, /* SAFEGUARD */
    {TYPE_NORMAL,1,0}, /* PAIN_SPLIT */
    {TYPE_FIRE,2,100}, /* SACRED_FIRE */
    {TYPE_GROUND,2,1}, /* MAGNITUDE */
    {TYPE_FIGHTING,2,100}, /* DYNAMIC_PUNCH */
    {TYPE_BUG,2,120}, /* MEGAHORN */
    {TYPE_DRAGON,2,60}, /* DRAGON_BREATH */
    {TYPE_NORMAL,1,0}, /* BATON_PASS */
    {TYPE_NORMAL,1,0}, /* ENCORE */
    {TYPE_DARK,2,40}, /* PURSUIT */
    {TYPE_NORMAL,2,20}, /* RAPID_SPIN */
    {TYPE_NORMAL,1,0}, /* SWEET_SCENT */
    {TYPE_STEEL,2,100}, /* IRON_TAIL */
    {TYPE_STEEL,2,50}, /* METAL_CLAW */
    {TYPE_FIGHTING,2,70}, /* VITAL_THROW */
    {TYPE_NORMAL,1,0}, /* MORNING_SUN */
    {TYPE_GRASS,1,0}, /* SYNTHESIS */
    {TYPE_NORMAL,1,0}, /* MOONLIGHT */
    {TYPE_NORMAL,6,1}, /* HIDDEN_POWER */
    {TYPE_FIGHTING,2,100}, /* CROSS_CHOP */
    {TYPE_DRAGON,2,40}, /* TWISTER */
    {TYPE_WATER,1,0}, /* RAIN_DANCE */
    {TYPE_FIRE,1,0}, /* SUNNY_DAY */
    {TYPE_DARK,2,80}, /* CRUNCH */
    {TYPE_PSYCHIC,4,1}, /* MIRROR_COAT */
    {TYPE_NORMAL,1,0}, /* PSYCH_UP */
    {TYPE_NORMAL,2,80}, /* EXTREME_SPEED */
    {TYPE_ROCK,2,60}, /* ANCIENT_POWER */
    {TYPE_GHOST,2,80}, /* SHADOW_BALL */
    {TYPE_PSYCHIC,5,80}, /* FUTURE_SIGHT */
    {TYPE_FIGHTING,2,20}, /* ROCK_SMASH */
    {TYPE_WATER,2,15}, /* WHIRLPOOL */
    {TYPE_DARK,5,10}, /* BEAT_UP */
    {TYPE_NORMAL,2,40}, /* FAKE_OUT */
    {TYPE_NORMAL,2,50}, /* UPROAR */
    {TYPE_NORMAL,1,0}, /* STOCKPILE */
    {TYPE_NORMAL,4,100}, /* SPIT_UP */
    {TYPE_NORMAL,1,0}, /* SWALLOW */
    {TYPE_FIRE,2,100}, /* HEAT_WAVE */
    {TYPE_ICE,1,0}, /* HAIL */
    {TYPE_DARK,1,0}, /* TORMENT */
    {TYPE_DARK,1,0}, /* FLATTER */
    {TYPE_FIRE,1,0}, /* WILL_O_WISP */
    {TYPE_DARK,1,0}, /* MEMENTO */
    {TYPE_NORMAL,2,70}, /* FACADE */
    {TYPE_FIGHTING,2,150}, /* FOCUS_PUNCH */
    {TYPE_NORMAL,2,60}, /* SMELLING_SALT */
    {TYPE_NORMAL,1,0}, /* FOLLOW_ME */
    {TYPE_NORMAL,5,0}, /* NATURE_POWER */
    {TYPE_ELECTRIC,1,0}, /* CHARGE */
    {TYPE_DARK,1,0}, /* TAUNT */
    {TYPE_NORMAL,1,0}, /* HELPING_HAND */
    {TYPE_PSYCHIC,1,0}, /* TRICK */
    {TYPE_PSYCHIC,1,0}, /* ROLE_PLAY */
    {TYPE_NORMAL,1,0}, /* WISH */
    {TYPE_NORMAL,5,0}, /* ASSIST */
    {TYPE_GRASS,1,0}, /* INGRAIN */
    {TYPE_FIGHTING,2,120}, /* SUPERPOWER */
    {TYPE_PSYCHIC,1,0}, /* MAGIC_COAT */
    {TYPE_NORMAL,1,0}, /* RECYCLE */
    {TYPE_FIGHTING,2,60}, /* REVENGE */
    {TYPE_FIGHTING,2,75}, /* BRICK_BREAK */
    {TYPE_NORMAL,1,0}, /* YAWN */
    {TYPE_DARK,2,20}, /* KNOCK_OFF */
    {TYPE_NORMAL,4,1}, /* ENDEAVOR */
    {TYPE_FIRE,2,150}, /* ERUPTION */
    {TYPE_PSYCHIC,1,0}, /* SKILL_SWAP */
    {TYPE_PSYCHIC,1,0}, /* IMPRISON */
    {TYPE_NORMAL,1,0}, /* REFRESH */
    {TYPE_GHOST,1,0}, /* GRUDGE */
    {TYPE_DARK,1,0}, /* SNATCH */
    {TYPE_NORMAL,2,70}, /* SECRET_POWER */
    {TYPE_WATER,2,60}, /* DIVE */
    {TYPE_FIGHTING,2,15}, /* ARM_THRUST */
    {TYPE_NORMAL,1,0}, /* CAMOUFLAGE */
    {TYPE_BUG,1,0}, /* TAIL_GLOW */
    {TYPE_PSYCHIC,2,70}, /* LUSTER_PURGE */
    {TYPE_PSYCHIC,2,70}, /* MIST_BALL */
    {TYPE_FLYING,1,0}, /* FEATHER_DANCE */
    {TYPE_NORMAL,1,0}, /* TEETER_DANCE */
    {TYPE_FIRE,2,85}, /* BLAZE_KICK */
    {TYPE_GROUND,1,0}, /* MUD_SPORT */
    {TYPE_ICE,2,30}, /* ICE_BALL */
    {TYPE_GRASS,2,60}, /* NEEDLE_ARM */
    {TYPE_NORMAL,1,0}, /* SLACK_OFF */
    {TYPE_NORMAL,2,90}, /* HYPER_VOICE */
    {TYPE_POISON,2,50}, /* POISON_FANG */
    {TYPE_NORMAL,2,75}, /* CRUSH_CLAW */
    {TYPE_FIRE,2,150}, /* BLAST_BURN */
    {TYPE_WATER,2,150}, /* HYDRO_CANNON */
    {TYPE_STEEL,2,100}, /* METEOR_MASH */
    {TYPE_GHOST,2,30}, /* ASTONISH */
    {TYPE_NORMAL,5,50}, /* WEATHER_BALL */
    {TYPE_GRASS,1,0}, /* AROMATHERAPY */
    {TYPE_DARK,1,0}, /* FAKE_TEARS */
    {TYPE_FLYING,2,55}, /* AIR_CUTTER */
    {TYPE_FIRE,2,140}, /* OVERHEAT */
    {TYPE_NORMAL,1,0}, /* ODOR_SLEUTH */
    {TYPE_ROCK,2,50}, /* ROCK_TOMB */
    {TYPE_BUG,2,60}, /* SILVER_WIND */
    {TYPE_STEEL,1,0}, /* METAL_SOUND */
    {TYPE_GRASS,1,0}, /* GRASS_WHISTLE */
    {TYPE_NORMAL,1,0}, /* TICKLE */
    {TYPE_PSYCHIC,1,0}, /* COSMIC_POWER */
    {TYPE_WATER,2,150}, /* WATER_SPOUT */
    {TYPE_BUG,2,75}, /* SIGNAL_BEAM */
    {TYPE_GHOST,2,60}, /* SHADOW_PUNCH */
    {TYPE_PSYCHIC,2,80}, /* EXTRASENSORY */
    {TYPE_FIGHTING,2,85}, /* SKY_UPPERCUT */
    {TYPE_GROUND,2,15}, /* SAND_TOMB */
    {TYPE_ICE,4,1}, /* SHEER_COLD */
    {TYPE_WATER,2,95}, /* MUDDY_WATER */
    {TYPE_GRASS,2,10}, /* BULLET_SEED */
    {TYPE_FLYING,2,60}, /* AERIAL_ACE */
    {TYPE_ICE,2,10}, /* ICICLE_SPEAR */
    {TYPE_STEEL,1,0}, /* IRON_DEFENSE */
    {TYPE_NORMAL,1,0}, /* BLOCK */
    {TYPE_NORMAL,1,0}, /* HOWL */
    {TYPE_DRAGON,2,80}, /* DRAGON_CLAW */
    {TYPE_GRASS,2,150}, /* FRENZY_PLANT */
    {TYPE_FIGHTING,1,0}, /* BULK_UP */
    {TYPE_FLYING,2,85}, /* BOUNCE */
    {TYPE_GROUND,2,55}, /* MUD_SHOT */
    {TYPE_POISON,2,50}, /* POISON_TAIL */
    {TYPE_NORMAL,2,40}, /* COVET */
    {TYPE_ELECTRIC,2,120}, /* VOLT_TACKLE */
    {TYPE_GRASS,2,60}, /* MAGICAL_LEAF */
    {TYPE_WATER,1,0}, /* WATER_SPORT */
    {TYPE_PSYCHIC,1,0}, /* CALM_MIND */
    {TYPE_GRASS,2,70}, /* LEAF_BLADE */
    {TYPE_DRAGON,1,0}, /* DRAGON_DANCE */
    {TYPE_ROCK,2,25}, /* ROCK_BLAST */
    {TYPE_ELECTRIC,2,60}, /* SHOCK_WAVE */
    {TYPE_WATER,2,60}, /* WATER_PULSE */
    {TYPE_STEEL,5,120}, /* DOOM_DESIRE */
    {TYPE_PSYCHIC,2,140}, /* PSYCHO_BOOST */
};
static const struct battle_matchup gen3_matchups[]={
    {TYPE_NORMAL,TYPE_ROCK,2},
    {TYPE_NORMAL,TYPE_STEEL,2},
    {TYPE_FIRE,TYPE_FIRE,2},
    {TYPE_FIRE,TYPE_WATER,2},
    {TYPE_FIRE,TYPE_GRASS,8},
    {TYPE_FIRE,TYPE_ICE,8},
    {TYPE_FIRE,TYPE_BUG,8},
    {TYPE_FIRE,TYPE_ROCK,2},
    {TYPE_FIRE,TYPE_DRAGON,2},
    {TYPE_FIRE,TYPE_STEEL,8},
    {TYPE_WATER,TYPE_FIRE,8},
    {TYPE_WATER,TYPE_WATER,2},
    {TYPE_WATER,TYPE_GRASS,2},
    {TYPE_WATER,TYPE_GROUND,8},
    {TYPE_WATER,TYPE_ROCK,8},
    {TYPE_WATER,TYPE_DRAGON,2},
    {TYPE_ELECTRIC,TYPE_WATER,8},
    {TYPE_ELECTRIC,TYPE_ELECTRIC,2},
    {TYPE_ELECTRIC,TYPE_GRASS,2},
    {TYPE_ELECTRIC,TYPE_GROUND,0},
    {TYPE_ELECTRIC,TYPE_FLYING,8},
    {TYPE_ELECTRIC,TYPE_DRAGON,2},
    {TYPE_GRASS,TYPE_FIRE,2},
    {TYPE_GRASS,TYPE_WATER,8},
    {TYPE_GRASS,TYPE_GRASS,2},
    {TYPE_GRASS,TYPE_POISON,2},
    {TYPE_GRASS,TYPE_GROUND,8},
    {TYPE_GRASS,TYPE_FLYING,2},
    {TYPE_GRASS,TYPE_BUG,2},
    {TYPE_GRASS,TYPE_ROCK,8},
    {TYPE_GRASS,TYPE_DRAGON,2},
    {TYPE_GRASS,TYPE_STEEL,2},
    {TYPE_ICE,TYPE_WATER,2},
    {TYPE_ICE,TYPE_GRASS,8},
    {TYPE_ICE,TYPE_ICE,2},
    {TYPE_ICE,TYPE_GROUND,8},
    {TYPE_ICE,TYPE_FLYING,8},
    {TYPE_ICE,TYPE_DRAGON,8},
    {TYPE_ICE,TYPE_STEEL,2},
    {TYPE_ICE,TYPE_FIRE,2},
    {TYPE_FIGHTING,TYPE_NORMAL,8},
    {TYPE_FIGHTING,TYPE_ICE,8},
    {TYPE_FIGHTING,TYPE_POISON,2},
    {TYPE_FIGHTING,TYPE_FLYING,2},
    {TYPE_FIGHTING,TYPE_PSYCHIC,2},
    {TYPE_FIGHTING,TYPE_BUG,2},
    {TYPE_FIGHTING,TYPE_ROCK,8},
    {TYPE_FIGHTING,TYPE_DARK,8},
    {TYPE_FIGHTING,TYPE_STEEL,8},
    {TYPE_POISON,TYPE_GRASS,8},
    {TYPE_POISON,TYPE_POISON,2},
    {TYPE_POISON,TYPE_GROUND,2},
    {TYPE_POISON,TYPE_ROCK,2},
    {TYPE_POISON,TYPE_GHOST,2},
    {TYPE_POISON,TYPE_STEEL,0},
    {TYPE_GROUND,TYPE_FIRE,8},
    {TYPE_GROUND,TYPE_ELECTRIC,8},
    {TYPE_GROUND,TYPE_GRASS,2},
    {TYPE_GROUND,TYPE_POISON,8},
    {TYPE_GROUND,TYPE_FLYING,0},
    {TYPE_GROUND,TYPE_BUG,2},
    {TYPE_GROUND,TYPE_ROCK,8},
    {TYPE_GROUND,TYPE_STEEL,8},
    {TYPE_FLYING,TYPE_ELECTRIC,2},
    {TYPE_FLYING,TYPE_GRASS,8},
    {TYPE_FLYING,TYPE_FIGHTING,8},
    {TYPE_FLYING,TYPE_BUG,8},
    {TYPE_FLYING,TYPE_ROCK,2},
    {TYPE_FLYING,TYPE_STEEL,2},
    {TYPE_PSYCHIC,TYPE_FIGHTING,8},
    {TYPE_PSYCHIC,TYPE_POISON,8},
    {TYPE_PSYCHIC,TYPE_PSYCHIC,2},
    {TYPE_PSYCHIC,TYPE_DARK,0},
    {TYPE_PSYCHIC,TYPE_STEEL,2},
    {TYPE_BUG,TYPE_FIRE,2},
    {TYPE_BUG,TYPE_GRASS,8},
    {TYPE_BUG,TYPE_FIGHTING,2},
    {TYPE_BUG,TYPE_POISON,2},
    {TYPE_BUG,TYPE_FLYING,2},
    {TYPE_BUG,TYPE_PSYCHIC,8},
    {TYPE_BUG,TYPE_GHOST,2},
    {TYPE_BUG,TYPE_DARK,8},
    {TYPE_BUG,TYPE_STEEL,2},
    {TYPE_ROCK,TYPE_FIRE,8},
    {TYPE_ROCK,TYPE_ICE,8},
    {TYPE_ROCK,TYPE_FIGHTING,2},
    {TYPE_ROCK,TYPE_GROUND,2},
    {TYPE_ROCK,TYPE_FLYING,8},
    {TYPE_ROCK,TYPE_BUG,8},
    {TYPE_ROCK,TYPE_STEEL,2},
    {TYPE_GHOST,TYPE_NORMAL,0},
    {TYPE_GHOST,TYPE_PSYCHIC,8},
    {TYPE_GHOST,TYPE_DARK,2},
    {TYPE_GHOST,TYPE_STEEL,2},
    {TYPE_GHOST,TYPE_GHOST,8},
    {TYPE_DRAGON,TYPE_DRAGON,8},
    {TYPE_DRAGON,TYPE_STEEL,2},
    {TYPE_DARK,TYPE_FIGHTING,2},
    {TYPE_DARK,TYPE_PSYCHIC,8},
    {TYPE_DARK,TYPE_GHOST,8},
    {TYPE_DARK,TYPE_DARK,2},
    {TYPE_DARK,TYPE_STEEL,2},
    {TYPE_STEEL,TYPE_FIRE,2},
    {TYPE_STEEL,TYPE_WATER,2},
    {TYPE_STEEL,TYPE_ELECTRIC,2},
    {TYPE_STEEL,TYPE_ICE,8},
    {TYPE_STEEL,TYPE_ROCK,8},
    {TYPE_STEEL,TYPE_STEEL,2},
    {TYPE_NORMAL,TYPE_GHOST,0},
    {TYPE_FIGHTING,TYPE_GHOST,0},
};
